# Generated by Django 5.1.1 on 2024-10-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_assigned_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assigned_at',
            new_name='assigned_to',
        ),
    ]
